# Generated by Django 3.1 on 2021-01-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sarpanch',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a validated Sarpanch.', verbose_name='Sarpanch status'),
        ),
    ]
