# Generated by Django 3.1 on 2020-11-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='paramkpr', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
