# Generated by Django 3.1 on 2021-01-15 17:57

import ckeditor_uploader.fields
import content.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=150, unique_for_date=True)),
                ('sub_title', models.CharField(help_text='A short description of the post', max_length=512)),
                ('thumbnail', models.ImageField(blank=True, default='thumbnails/default.png', help_text='Upload a 200x200 image less than 256kb.', null=True, upload_to='thumbnails/', validators=[content.utils.validate_thumbnail_size])),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
